services:

  api:
    environment:
      ENVIRONMENT: test
    volumes:
      - ./tests/fixtures/test-workspace:/data/test-workspace

  worker:
    volumes:
      - ./tests/fixtures/test-workspace:/data/test-workspace
