"""add file scan metadata

Revision ID: 2eb861747090
Revises: 59f937f1c045
Create Date: 2026-08-28 19:09:23.573801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb861747090'
down_revision: Union[str, Sequence[str], None] = '59f937f1c045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('files', sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('files', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'status')
    op.drop_column('files', 'last_scanned_at')
    op.drop_column('files', 'modified_at')
    # ### end Alembic commands ###
