"""add job scan warnings

Revision ID: 84904aaf96a8
Revises: d5de3b2ac498
Create Date: 2026-09-01 15:23:32.228105

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84904aaf96a8"
down_revision: str | Sequence[str] | None = "d5de3b2ac498"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("skipped_files", sa.Integer(), nullable=False))
    op.add_column("jobs", sa.Column("permission_errors", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "permission_errors")
    op.drop_column("jobs", "skipped_files")
    # ### end Alembic commands ###
