"""add job progress metadata

Revision ID: d5de3b2ac498
Revises: 958045f32f99
Create Date: 2026-08-31 21:35:16.514296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5de3b2ac498'
down_revision: Union[str, Sequence[str], None] = '958045f32f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('total_files', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'finished_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'total_files')
    # ### end Alembic commands ###
